/* Product catalog — items 1-6 use the client's supplied pictures & names.
   Urdu copy (short/description/benefits/dosage/urdu) for items 1-6 is written in the
   same format: item 6 (Sperm Plus Tablets) is VERBATIM from
   https://hakeembabar.health/products/spermplus (incl. source spacing quirks like
   "حلکیلئے" — do not "fix"); items 1-5 are ORIGINAL Urdu copy written to match each
   product's own label/picture claims (ingredient lists provisional — client to verify).
   Categories/sizes aligned to the pictures (30 ml oil, 30/90 capsule counts, course/set).
   Items 7-10 are numbered placeholders; prices for items 1-5 are still dummy. */

export type Product = {
  slug: string;
  name: string;
  urdu: string;
  category: string; // Majoon | Khamira | Sharbat | Roghan | Habbe | Capsule
  size: string;
  price: number;
  compareAt?: number;
  img: string;
  rating: number;
  reviews: number;
  sold24: number; // dummy "sold in last 24 hours"
  viewing: number; // dummy "viewing right now"
  inStock: boolean;
  bestseller?: boolean;
  fresh?: boolean; // New Arrivals tab
  short: string;
  description: string[];
  benefits: string[];
  dosage: string;
  pairWith: string[]; // slugs for "Pairs well with"
};

export const CATEGORIES = ["Majoon", "Khamira", "Sharbat", "Roghan", "Habbe", "Capsule"];

export const products: Product[] = [
  {
    slug: "majoon-e-shahi",
    name: "Joint Sukoon Oil",
    urdu: "جونٹ سکون آئل",
    category: "Roghan",
    size: "30 ml",
    price: 3500,
    compareAt: 4200,
    img: "/images/joint-sukoon-oil.jpg",
    rating: 4.8,
    reviews: 612,
    sold24: 38,
    viewing: 25,
    inStock: true,
    bestseller: true,
    fresh: false,
    short: "جونٹ سکون آئل جوڑوں کے درد، گھٹنوں کی جکڑن اور کمر درد کیلئے تیار کیا گیا ایک خالص قدرتی ہربل آئل ہے۔",
    description: [
      "## مختصر تعارف",
      "جونٹ سکون آئل جوڑوں کے درد اور ہڈیوں کی تکلیف کے حل کیلئے تیار کیا گیا ایک خالص قدرتی ہربل فارمولا ہے۔ یہ آئل خاص طور پر جوڑوں کے درد، گھٹنوں کی جکڑن، کمر درد، کندھے کے درد اور گٹھیا جیسے مسائل میں نہایت مؤثر ہے۔ باقاعدہ مالش سے یہ درد میں آرام، جوڑوں کی لچک اور حرکت میں آسانی فراہم کرتا ہے۔",
      "## ✨ تفصیلی تعارف",
      "جونٹ سکون آئل ایک آزمودہ اور محفوظ نسخہ ہے جو خاص طور پر ان افراد کیلئے بنایا گیا ہے جو جوڑوں کے درد یا بڑھتی عمر کی وجہ سے ہونے والی تکلیف کا شکار ہیں۔",
      "✔️ جوڑوں کے درد کیلئے – گہرائی تک رسائی کر کے درد میں فوری اور دیرپا آرام فراہم کرتا ہے۔",
      "✔️ گھٹنوں کی جکڑن کیلئے – جوڑوں کی اکڑن دور کر کے حرکت میں آسانی پیدا کرتا ہے۔",
      "✔️ کمر اور کندھے کے درد کیلئے – پٹھوں اور رگوں کو سکون پہنچا کر تکلیف کم کرتا ہے۔",
      "✔️ گٹھیا اور سوزش کیلئے – جوڑوں کی سوزش میں کمی لا کر آرام دیتا ہے۔",
      "✔️ حرکت میں بہتری کیلئے – باقاعدہ مالش سے چلنے پھرنے میں آسانی بحال کرتا ہے۔",
      "✔️ عمومی کمزوری کیلئے – جوڑوں اور ہڈیوں کی مضبوطی میں مدد دیتا ہے۔",
      "یہ آئل مکمل طور پر ہربل، کیمیکل فری اور روزانہ استعمال کیلئے محفوظ ہے۔",
      "## 🌱 فوائد ایک نظر میں",
      "جوڑوں کے درد میں آرام",
      "گھٹنوں، کمر اور کندھے کے درد میں مؤثر",
      "سوزش میں کمی اور حرکت میں بہتری",
      "100% قدرتی جڑی بوٹیوں سے تیار کردہ",
      "کوئی سائیڈ ایفیکٹ نہیں",
      "## ⚡ اجزاء (Ingredients)",
      "جونٹ سکون آئل اعلیٰ معیار کی قدرتی جڑی بوٹیوں سے تیار کیا گیا ہے جنہیں صدیوں سے جوڑوں کی صحت کیلئے استعمال کیا جا رہا ہے:",
      "ہلدی",
      "کالی مرچ",
      "پودینہ",
      "تل کا تیل",
      "اور دیگر جوڑوں کی صحت دوست اجزاء",
      "## 🌟 کیوں منتخب کریں جونٹ سکون آئل؟",
      "✅ قدرتی اور محفوظ",
      "✅ جوڑوں کے درد کیلئے مؤثر",
      "✅ تیزی سے جذب ہونے والی ترکیب",
      "✅ روزانہ استعمال کیلئے بہترین",
    ],
    benefits: [
      "جوڑوں کے درد میں آرام",
      "گھٹنوں، کمر اور کندھے کے درد میں مؤثر",
      "سوزش میں کمی اور حرکت میں بہتری",
      "100% قدرتی جڑی بوٹیوں سے تیار کردہ",
      "کوئی سائیڈ ایفیکٹ نہیں",
    ],
    dosage: "متاثرہ جگہ پر تھوڑی سی مقدار لے کر ہلکی مالش کریں، دن میں دو تین بار، یا اپنے حکیم کی ہدایت کے مطابق۔",
    pairWith: ["roghan-baadam-shirin", "khamira-gilo-himalayi"],
  },
  {
    slug: "majoon-muqavvi-dimagh",
    name: "Prozon Premium Prostate Support",
    urdu: "پرو زون پریمیم پروسٹیٹ سپورٹ",
    category: "Capsule",
    size: "30 Capsules",
    price: 3200,
    img: "/images/prozon-prostate-support.jpg",
    rating: 4.9,
    reviews: 284,
    sold24: 21,
    viewing: 17,
    inStock: true,
    bestseller: true,
    fresh: false,
    short: "پرو زون سا پالمٹو ایکسٹریکٹ کے ساتھ پروسٹیٹ کی صحت اور پیشاب کے بہاؤ کی حمایت کیلئے تیار کیا گیا ایک خالص قدرتی ہربل فارمولا ہے۔",
    description: [
      "## مختصر تعارف",
      "پرو زون ایک خالص قدرتی ہربل فارمولا ہے جو پروسٹیٹ کی صحت کو بہتر بنانے اور پیشاب کی تکلیف کے حل کیلئے تیار کیا گیا ہے۔ یہ فارمولا خاص طور پر بار بار پیشاب آنا، پیشاب میں جلن، پیشاب کی نالی کی جکڑن اور پروسٹیٹ کے بڑھ جاتے مسائل میں نہایت مؤثر ہے۔ باقاعدہ استعمال سے یہ پیشاب کا نظام درست کرتا ہے اور پروسٹیٹ کے صحت مند کام کو برقرار رکھتا ہے۔",
      "## ✨ تفصیلی تعارف",
      "پرو زون ایک آزمودہ اور محفوظ نسخہ ہے جو خاص طور پر ان مردوں کیلئے بنایا گیا ہے جو بڑھتی عمر یا پروسٹیٹ کے مسائل کا شکار ہیں۔",
      "✔️ بار بار پیشاب کیلئے – دن اور رات بار بار پیشاب آنے کی شکایت میں بتدریج بہتری لاتا ہے۔",
      "✔️ پیشاب میں جلن کیلئے – پیشاب کی نالی کو سکون دے کر جلن اور تکلیف کم کرتا ہے۔",
      "✔️ کمزور بہاؤ کیلئے – پیشاب کے مکمل اور آزادانہ بہاؤ کو بحال کرنے میں مدد دیتا ہے۔",
      "✔️ پروسٹیٹ کے بڑھنے کیلئے – پروسٹیٹ کے صحت مند سائز اور کام کو برقرار رکھتا ہے۔",
      "✔️ نیند میں خلل کیلئے – رات کو بار بار جاگنے کی عادت میں کمی لا کر آرام دہ نیند دلاتا ہے۔",
      "✔️ عمومی کمزوری کیلئے – پروسٹیٹ کی صحت کے ذریعے مردانہ توانائی میں اضافہ کرتا ہے۔",
      "یہ فارمولا مکمل طور پر ہربل، کیمیکل فری اور روزانہ استعمال کیلئے محفوظ ہے۔",
      "## 🌱 فوائد ایک نظر میں",
      "پروسٹیٹ کے کام کی قدرتی حمایت",
      "پیشاب کے بہاؤ میں بہتری",
      "سا پالمٹو ایکسٹریکٹ کی مؤثر طاقت",
      "پیشاب اور پروسٹیٹ کی مکمل صحت",
      "کوئی سائیڈ ایفیکٹ نہیں",
      "## ⚡ اجزاء (Ingredients)",
      "پرو زون اعلیٰ معیار کی قدرتی جڑی بوٹیوں سے تیار کیا گیا ہے جنہیں صدیوں سے پیشاب اور پروسٹیٹ کی صحت کیلئے استعمال کیا جا رہا ہے:",
      "سا پالمٹو ایکسٹریکٹ (Saw Palmetto)",
      "کدو کے بیج",
      "گوکشور",
      "آملہ",
      "اور دیگر پیشاب اور پروسٹیٹ صحت دوست اجزاء",
      "## 🌟 کیوں منتخب کریں پرو زون؟",
      "✅ قدرتی اور محفوظ",
      "✅ سا پالمٹو ایکسٹریکٹ کے ساتھ",
      "✅ پروسٹیٹ اور پیشاب کی صحت کیلئے مؤثر",
      "✅ روزانہ استعمال کیلئے بہترین",
    ],
    benefits: [
      "پروسٹیٹ کے کام کی قدرتی حمایت",
      "پیشاب کے بہاؤ میں بہتری",
      "سا پالمٹو ایکسٹریکٹ کی مؤثر طاقت",
      "پیشاب اور پروسٹیٹ کی مکمل صحت",
      "کوئی سائیڈ ایفیکٹ نہیں",
    ],
    dosage: "روزانہ استعمال کیلئے بہترین، یا اپنے حکیم کی ہدایت کے مطابق۔",
    pairWith: ["itrifal-ustukhuddus", "roghan-baadam-shirin"],
  },
  {
    slug: "majoon-jograj-guggul",
    name: "Men's Vitality Support",
    urdu: "مینز وٹالٹی سپورٹ",
    category: "Capsule",
    size: "1 Course",
    price: 1950,
    compareAt: 2400,
    img: "/images/mens-vitality-support.jpg",
    rating: 4.6,
    reviews: 176,
    sold24: 12,
    viewing: 9,
    inStock: true,
    fresh: false,
    short: "مینز وٹالٹی سپورٹ جریان، احتلام اور سرعت انزال جیسے مسائل کے حل کیلئے تیار کیا گیا ایک خالص قدرتی ہربل فارمولا ہے۔",
    description: [
      "## مختصر تعارف",
      "مینز وٹالٹی سپورٹ مردانہ صحت کو بہتر بنانے اور جنسی مسائل کے حل کیلئے تیار کیا گیا ایک خالص قدرتی ہربل فارمولا ہے۔ یہ فارمولا خاص طور پر جریان، احتلام اور سرعت انزال جیسے مسائل میں نہایت مؤثر ہے۔ مکمل کورس کے باقاعدہ استعمال سے یہ مردانہ طاقت میں اضافہ کرتا ہے اور اعصاب کو مضبوط بناتا ہے۔",
      "## ✨ تفصیلی تعارف",
      "مینز وٹالٹی سپورٹ ایک آزمودہ اور محفوظ نسخہ ہے جو خاص طور پر ان مردوں کیلئے بنایا گیا ہے جو احتلام، جریان یا سرعت انزال کے مسائل کا شکار ہیں۔",
      "✔️ احتلام کیلئے – نیند میں انزال کی شکایت میں بتدریج بہتری لاتا ہے۔",
      "✔️ سرعت انزال کیلئے – انزال کا وقت بڑھا کر مردانہ کارکردگی بہتر بناتا ہے۔",
      "✔️ جریان کیلئے – بے اختیار اخراج کی شکایت کو قابو میں لا کر کمزوری دور کرتا ہے۔",
      "✔️ مردانہ طاقت کیلئے – جسمانی اور مردانہ توانائی میں اضافہ کرتا ہے۔",
      "✔️ اعصاب کی مضبوطی کیلئے – مردانہ اعصاب کو مضبوط بناتا ہے۔",
      "✔️ عمومی کمزوری کیلئے – تھکاوٹ اور سستی دور کر کے پُرتوان زندگی عطا کرتا ہے۔",
      "یہ فارمولا مکمل طور پر ہربل، کیمیکل فری اور روزانہ استعمال کیلئے محفوظ ہے۔",
      "## 🌱 فوائد ایک نظر میں",
      "احتلام اور جریان میں بتدریج بہتری",
      "سرعت انزال کے مسئلے میں فائدہ",
      "مردانہ طاقت اور توانائی میں اضافہ",
      "اعصاب کی مضبوطی",
      "مکمل کورس کے ساتھ دیرپا فائدہ",
      "## ⚡ اجزاء (Ingredients)",
      "مینز وٹالٹی سپورٹ اعلیٰ معیار کی قدرتی جڑی بوٹیوں سے تیار کیا گیا ہے جنہیں صدیوں سے مردانہ صحت کیلئے استعمال کیا جا رہا ہے:",
      "اشوگندھا",
      "سفوف کونچ",
      "جائفل",
      "شلجیت",
      "اور دیگر مردانہ صحت دوست اجزاء",
      "## 🌟 کیوں منتخب کریں مینز وٹالٹی سپورٹ؟",
      "✅ قدرتی اور محفوظ",
      "✅ احتلام اور سرعت انزال کیلئے مؤثر",
      "✅ مردانہ طاقت میں اضافہ",
      "✅ مکمل کورس کے ساتھ بہترین نتائج",
    ],
    benefits: [
      "احتلام اور جریان میں بتدریج بہتری",
      "سرعت انزال کے مسئلے میں فائدہ",
      "مردانہ طاقت اور توانائی میں اضافہ",
      "اعصاب کی مضبوطی",
      "مکمل کورس کے ساتھ دیرپا فائدہ",
    ],
    dosage: "مکمل کورس باقاعدگی سے مکمل کریں، یا اپنے حکیم کی ہدایت کے مطابق۔",
    pairWith: ["roghan-babchi", "khamira-abresham"],
  },
  {
    slug: "khamira-gilo-himalayi",
    name: "Donkey Oil & Golden Capsule",
    urdu: "ڈنکی آئل اینڈ گولڈن کیپسول",
    category: "Roghan",
    size: "1 Set",
    price: 2800,
    compareAt: 3400,
    img: "/images/donkey-oil-golden-capsule.jpg",
    rating: 4.9,
    reviews: 398,
    sold24: 27,
    viewing: 19,
    inStock: true,
    bestseller: true,
    fresh: false,
    short: "ڈنکی آئل اینڈ گولڈن کیپسول مردانہ طاقت اور مضبوطی کیلئے روغن اور کیپسول پر مشتمل ایک خالص قدرتی ہربل مجموعہ ہے۔",
    description: [
      "## مختصر تعارف",
      "ڈنکی آئل اینڈ گولڈن کیپسول مردانہ طاقت اور مضبوطی کے حل کیلئے تیار کیا گیا ایک خالص قدرتی ہربل مجموعہ ہے۔ یہ مجموعہ دو حصوں پر مشتمل ہے: روغن صرف خارجی استعمال کیلئے ہے جبکہ گولڈن کیپسول جسم کی اندرونی طاقت کیلئے ہیں۔ باقاعدہ استعمال سے یہ مردانہ طاقت میں اضافہ کرتا ہے اور پٹھوں و اعصاب کو مضبوط بناتا ہے۔",
      "## ✨ تفصیلی تعارف",
      "ڈنکی آئل اینڈ گولڈن کیپسول ایک آزمودہ اور محفوظ نسخہ ہے جو خاص طور پر ان مردوں کیلئے بنایا گیا ہے جو مردانہ کمزوری اور سستی کا شکار ہیں۔",
      "✔️ مردانہ طاقت کیلئے – جسمانی اور مردانہ توانائی میں اضافہ کرتا ہے۔",
      "✔️ مضبوطی کیلئے – روغن کی مالش سے پٹھوں اور اعصاب مضبوط بناتا ہے۔",
      "✔️ عمومی کمزوری کیلئے – گولڈن کیپسول جسم کی اندرونی طاقت بحال کرتے ہیں۔",
      "✔️ تھکاوٹ کیلئے – دن بھر کی تھکاوٹ دور کر کے پُرتوانی دیتا ہے۔",
      "✔️ خالص روغن کیلئے – 100% قدرتی ہربل روغن جو صرف خارجی استعمال کیلئے ہے۔",
      "✔️ دیرپا فائدہ کیلئے – باقاعدہ استعمال سے نتیجے دیرپا اور مستقل رہتے ہیں۔",
      "یہ مجموعہ مکمل طور پر ہربل، کیمیکل فری اور ہدایت کے مطابق استعمال کیلئے محفوظ ہے۔",
      "## 🌱 فوائد ایک نظر میں",
      "مردانہ طاقت اور توانائی میں اضافہ",
      "مالش سے پٹھوں اور اعصاب کی مضبوطی",
      "گولڈن کیپسول سے اندرونی طاقت کی بحالی",
      "خالص قدرتی ہربل ترکیب",
      "کوئی سائیڈ ایفیکٹ نہیں",
      "## ⚡ اجزاء (Ingredients)",
      "ڈنکی آئل اینڈ گولڈن کیپسول اعلیٰ معیار کی قدرتی جڑی بوٹیوں سے تیار کیا گیا ہے جنہیں صدیوں سے مردانہ صحت کیلئے استعمال کیا جا رہا ہے:",
      "خالص روغنِ گدھا",
      "تل کا تیل",
      "جائفل",
      "اشوگندھا",
      "اور دیگر مردانہ صحت دوست اجزاء",
      "## 🌟 کیوں منتخب کریں ڈنکی آئل اینڈ گولڈن کیپسول؟",
      "✅ قدرتی اور محفوظ",
      "✅ روغن اور کیپسول کا مکمل مجموعہ",
      "✅ مردانہ مضبوطی کیلئے مؤثر",
      "✅ روزانہ استعمال کیلئے بہترین",
    ],
    benefits: [
      "مردانہ طاقت اور توانائی میں اضافہ",
      "مالش سے پٹھوں اور اعصاب کی مضبوطی",
      "گولڈن کیپسول سے اندرونی طاقت کی بحالی",
      "خالص قدرتی ہربل ترکیب",
      "کوئی سائیڈ ایفیکٹ نہیں",
    ],
    dosage: "روغن صرف خارجی استعمال کیلئے ہے: متاثرہ جگہ پر ہلکی مالش کریں، اور کیپسول روزانہ باقاعدگی سے استعمال کریں، یا اپنے حکیم کی ہدایت کے مطابق۔",
    pairWith: ["majoon-e-shahi", "sharbat-faulad"],
  },
  {
    slug: "khamira-abresham",
    name: "Pine Height",
    urdu: "پائن ہائٹ",
    category: "Capsule",
    size: "90 Capsules",
    price: 2400,
    img: "/images/pine-height.jpg",
    rating: 4.8,
    reviews: 221,
    sold24: 15,
    viewing: 11,
    inStock: true,
    fresh: true,
    short: "پائن ہائٹ قد میں اضافہ، ہڈیوں کی مضبوطی اور جسم کی نشوونما کیلئے تیار کیا گیا ایک خالص قدرتی ہربل فارمولا ہے۔",
    description: [
      "## مختصر تعارف",
      "پائن ہائٹ قد بڑھانے اور جسم کی نشوونما کے حل کیلئے تیار کیا گیا ایک خالص قدرتی ہربل فارمولا ہے۔ یہ فارمولا قد میں 2 سے 6 انچ تک اضافے کی خواہش رکھنے والے افراد کیلئے بہترین کورس ہے۔ باقاعدہ استعمال سے یہ ہڈیوں کو مضبوط بناتا ہے، قوت مدافعت بڑھاتا ہے اور جسمانی طاقت میں اضافہ کرتا ہے۔",
      "## ✨ تفصیلی تعارف",
      "پائن ہائٹ ایک آزمودہ اور محفوظ نسخہ ہے جو خاص طور پر ان افراد کیلئے بنایا گیا ہے جو اپنا قد بڑھانا اور بہتر نشوونما چاہتے ہیں۔",
      "✔️ قد بڑھانے کیلئے – قدرتی طریقے سے قد میں 2 سے 6 انچ تک اضافے میں مدد دیتا ہے۔",
      "✔️ ہڈیوں کی مضبوطی کیلئے – ہڈیوں کو مضبوط اور گنجان بناتا ہے۔",
      "✔️ نشوونما کیلئے – جسم کی قدرتی نشوونما کو فروغ دے کر بہترین قد دلاتا ہے۔",
      "✔️ قوت مدافعت کیلئے – بیماریوں سے حفاظت کیلئے مدافعت بڑھاتا ہے۔",
      "✔️ جسمانی طاقت کیلئے – جسم کو پُرتوان اور فعال بناتا ہے۔",
      "✔️ خود اعتمادی کیلئے – بہتر قد کے ساتھ خود اعتمادی بحال کرتا ہے۔",
      "یہ فارمولا مکمل طور پر ہربل، کیمیکل فری اور روزانہ استعمال کیلئے محفوظ ہے۔",
      "## 🌱 فوائد ایک نظر میں",
      "قد بڑھانے کی قدرتی حمایت",
      "ہڈیوں کو مضبوط بناتا ہے",
      "قوت مدافعت بڑھاتا ہے",
      "جسمانی طاقت میں اضافہ",
      "کوئی سائیڈ ایفیکٹ نہیں",
      "## ⚡ اجزاء (Ingredients)",
      "پائن ہائٹ اعلیٰ معیار کی قدرتی جڑی بوٹیوں سے تیار کیا گیا ہے جنہیں صدیوں سے قد اور نشوونما کی صحت کیلئے استعمال کیا جا رہا ہے:",
      "اشوگندھا",
      "آملہ",
      "سیلاجیت",
      "مصطگی",
      "اور دیگر قد و نشوونما صحت دوست اجزاء",
      "## 🌟 کیوں منتخب کریں پائن ہائٹ؟",
      "✅ قدرتی اور محفوظ",
      "✅ قد بڑھانے کیلئے مؤثر",
      "✅ ہڈیوں اور قوت مدافعت کیلئے بہترین",
      "✅ کوئی سائیڈ ایفیکٹ نہیں",
    ],
    benefits: [
      "قد بڑھانے کی قدرتی حمایت",
      "ہڈیوں کو مضبوط بناتا ہے",
      "قوت مدافعت بڑھاتا ہے",
      "جسمانی طاقت میں اضافہ",
      "کوئی سائیڈ ایفیکٹ نہیں",
    ],
    dosage: "مکمل کورس باقاعدگی سے مکمل کریں، یا اپنے حکیم کی ہدایت کے مطابق۔",
    pairWith: ["sharbat-bazoori-motadil", "majoon-e-shahi"],
  },
  {
    slug: "sharbat-faulad",
    name: "Sperm Plus Tablets",
    urdu: "سپرم پلس ٹیبلٹس",
    category: "Capsule",
    size: "1 Course",
    price: 3500,
    compareAt: 4400,
    img: "/images/sperm-plus.jpg",
    rating: 4.6,
    reviews: 189,
    sold24: 18,
    viewing: 13,
    inStock: true,
    fresh: true,
    short: "اسپرم پلس کیپسول ایک خالص قدرتی ہربل فارمولا ہے جو مردانہ صحت کو بہتر بنانے اور سپرم کے مسائل کے حلکیلئے تیار کیا گیا ہے۔",
    description: [
      "## مختصر تعارف",
      "اسپرم پلس کیپسول ایک خالص قدرتی ہربل فارمولا ہے جو مردانہ صحت کو بہتر بنانے اور سپرم کے مسائل کے حلکیلئے تیار کیا گیا ہے۔ یہ کیپسول خاص طور پر بے اولادی، سپرم کی کمی، نل اسپرم، ایزو اسپرمیا، نیکروسپرمیہ اور اولیگوسپرمیہ جیسے مسائل میں نہایت مؤثر ہے۔ باقاعدہ استعمال سے یہ سپرم کی مقدار اور معیار کو بہتر بناتا ہے اور مردانہ طاقت میں اضافہ کرتا ہے۔",
      "## ✨ تفصیلی تعارف",
      "اسپرم پلس کیپسول ایک آزمودہ اور محفوظ نسخہ ہے جو خاص طور پر ان مردوںکیلئے بنایا گیا ہے جو سپرم کی کمی یا تولیدی مسائل کا شکار ہیں۔",
      "✔️ بے اولادیکیلئے مؤثر – مردانہ بانجھ پن میں بہتری لا کر اولاد کا امکان بڑھاتا ہے۔",
      "✔️ سپرم کی کمی دورکرنےکیلئے – سپرم کی تعداد اور حرکت (حرکت پذیری) بڑھاتا ہے۔",
      "✔️ نل اسپرم اور ایزو اسپرمیاکیلئے – سپرم پیداوار کو بڑھا کر تولیدی صلاحیت میں اضافہ کرتا ہے۔",
      "✔️ نیکروسپرمیہ (مردہ سپرم)کیلئے – سپرم کے معیار کو بہتر بناتا ہے تاکہ صحت مند نطفہ پیدا ہوسکے۔",
      "✔️ اولیگوسپرمیہ (سپرم کی کمی)کیلئے – سپرم کی تعداد بڑھاتا ہے اور نطفہ مضبوط بناتا ہے۔",
      "✔️ عمومی کمزوریکیلئے – جسمانی اور مردانہ طاقت میں اضافہ کرتا ہے۔",
      "یہ کیپسول مکمل طور پر ہربل، کیمیکل فری اور روزانہ استعمالکیلئے محفوظ ہے۔",
      "## 🌱 فوائد ایک نظر میں",
      "مردانہ بانجھ پن (بے اولادی) میں بہتری",
      "سپرم کی تعداد اور حرکت میں اضافہ",
      "نل اسپرم اور ایزو اسپرمیا میں مؤثر",
      "نیکروسپرمیہ اور اولیگوسپرمیہ میں سپرم کا معیار بہتر",
      "جسمانی اور جنسی کمزوری میں طاقت بحال",
      "## ⚡ اجزاء (Ingredients)",
      "اسپرم پلس کیپسول اعلیٰ معیار کی قدرتی جڑی بوٹیوں سے تیار کیا گیا ہے جنہیں صدیوں سے مردانہ صحتکیلئے استعمال کیا جا رہا ہے:",
      "سفوف کونچ",
      "اشوگندھا",
      "آملہ",
      "جائفل",
      "اور دیگر جگر و مردانہ صحت دوست اجزاء",
      "## 🌟 کیوں منتخب کریں اسپرم پلس کیپسول؟",
      "✅ قدرتی اور محفوظ",
      "✅ بانجھ پن اور سپرم مسائلکیلئے مؤثر",
      "✅ مردانہ طاقت میں اضافہ",
      "✅ روزانہ استعمالکیلئے بہترین",
    ],
    benefits: [
      "مردانہ بانجھ پن (بے اولادی) میں بہتری",
      "سپرم کی تعداد اور حرکت میں اضافہ",
      "نل اسپرم اور ایزو اسپرمیا میں مؤثر",
      "نیکروسپرمیہ اور اولیگوسپرمیہ میں سپرم کا معیار بہتر",
      "جسمانی اور جنسی کمزوری میں طاقت بحال",
    ],
    dosage: "روزانہ استعمال کیلئے بہترین، یا اپنے حکیم کی ہدایت کے مطابق۔",
    pairWith: ["khamira-gilo-himalayi", "majoon-e-shahi"],
  },
  {
    slug: "sharbat-bazoori-motadil",
    name: "Product 7",
    urdu: "",
    category: "Sharbat",
    size: "500 ml",
    price: 2100,
    compareAt: 2500,
    img: "/images/p_syrup.png",
    rating: 4.7,
    reviews: 298,
    sold24: 22,
    viewing: 15,
    inStock: true,
    bestseller: true,
    fresh: false,
    short: "Cooling liver tonic sharbat with bazoori seeds — the classical choice for liver heat and summer fatigue.",
    description: [
      "Bazoori Motadil is a balanced (motadil) liver sharbat built around cooling bazoori seeds and delicate aromatic herbs. Classical physicians reached for it whenever the liver was hot, the temper short and the body tired.",
      "Taken chilled in summer, it is a family favourite for keeping the liver calm and the mood even.",
    ],
    benefits: [
      "Classical cooling liver tonic",
      "Eases liver heat and summer fatigue",
      "Supports calm, even mood",
      "Delicious served chilled",
    ],
    dosage: "Two tablespoons with water morning and evening, or as directed by your Hakeem.",
    pairWith: ["sharbat-faulad", "khamira-abresham"],
  },
  {
    slug: "roghan-babchi",
    name: "Product 8",
    urdu: "",
    category: "Roghan",
    size: "50 ml",
    price: 1450,
    img: "/images/p_oil.png",
    rating: 4.7,
    reviews: 241,
    sold24: 16,
    viewing: 21,
    inStock: true,
    fresh: false,
    short: "Classical babchi seed oil traditionally massaged on the skin to support even tone and natural colour.",
    description: [
      "Roghan Babchi is prepared by infusing babchi seeds — one of the most respected herbs in Unani dermatology — into a nourishing oil base under gentle heat.",
      "Applied locally with a light massage, it has long been used for skin tone, spots and dryness. A patch test is recommended before first use.",
    ],
    benefits: [
      "Traditional oil for skin tone and spots",
      "Supports naturally even, healthy skin",
      "Prepared from pure babchi seeds",
      "Light, fast-absorbing base oil",
    ],
    dosage: "Apply a few drops on affected skin twice daily with gentle massage, or as directed by your Hakeem.",
    pairWith: ["majoon-jograj-guggul", "roghan-baadam-shirin"],
  },
  {
    slug: "roghan-baadam-shirin",
    name: "Product 9",
    urdu: "",
    category: "Roghan",
    size: "100 ml",
    price: 1200,
    img: "/images/p_oil.png",
    rating: 4.8,
    reviews: 356,
    sold24: 30,
    viewing: 23,
    inStock: true,
    bestseller: true,
    fresh: false,
    short: "Pure sweet almond oil — the family classic for brain, hair, skin and gentle daily nourishment.",
    description: [
      "Cold-pressed from sweet almonds (baadam shirin), this clear golden oil is one of the most loved household oils in Unani tradition — a spoonful for the brain and body, a few drops for hair and skin.",
      "It is 100% pure with nothing added: no fragrance, no mineral oil, no preservatives.",
    ],
    benefits: [
      "100% pure cold-pressed sweet almond oil",
      "Traditionally taken for brain and body strength",
      "Excellent for hair, scalp and soft skin",
      "Safe for the whole family",
    ],
    dosage: "Half teaspoon daily for adults; a few drops for hair and skin as needed.",
    pairWith: ["majoon-e-shahi", "majoon-muqavvi-dimagh"],
  },
  {
    slug: "habbe-mumsik",
    name: "Product 10",
    urdu: "",
    category: "Habbe",
    size: "20 pills",
    price: 2200,
    compareAt: 2650,
    img: "/images/p_pills.png",
    rating: 4.8,
    reviews: 517,
    sold24: 34,
    viewing: 27,
    inStock: true,
    bestseller: true,
    fresh: false,
    short: "Classical herbal pills traditionally taken for male strength, stamina and confidence — discreet ordering.",
    description: [
      "Habbe Mumsik Titraje is one of the most prescribed classical compounds for male sexual health. Small pills of warming herbs are taken over a course of days, gently building strength rather than forcing it.",
      "Each pill is made from pure herbs — no modern pharmaceuticals — and is packed discreetly with plain, unmarked outer packaging.",
    ],
    benefits: [
      "Classical support for male strength and stamina",
      "Herbal course — no pharmaceutical drugs",
      "Builds gradually, dose by dose",
      "Discreet, unmarked packaging",
    ],
    dosage: "One pill at bedtime with warm milk on the days directed by your Hakeem.",
    pairWith: ["majoon-e-shahi", "roghan-baadam-shirin"],
  },
];

export const bySlug = (slug: string) => products.find((p) => p.slug === slug);
export const prevNext = (slug: string) => {
  const i = products.findIndex((p) => p.slug === slug);
  return { prev: products[(i - 1 + products.length) % products.length], next: products[(i + 1) % products.length] };
};
export const bestsellers = () => products.filter((p) => p.bestseller);
export const hotProducts = () => [...products].sort((a, b) => b.sold24 - a.sold24).slice(0, 8);
export const freshProducts = () => products.filter((p) => p.fresh);
export const saleProducts = () => products.filter((p) => p.compareAt);
export const alsoBought = (p: Product) =>
  products.filter((x) => x.slug !== p.slug && x.category === p.category)
    .concat(products.filter((x) => x.slug !== p.slug && x.category !== p.category))
    .slice(0, 4);
export const related = (p: Product) => p.pairWith.map(bySlug).filter(Boolean) as Product[];
